### ISSUE TITLE
vue-routerにて、トップページに遷移しない

### ISSUE THREAD

**Issue by nuno929** [michi-h0623/picsView#1]
# 解消方法
- 以下にて、deepWatchを試す
    - https://github.com/michi-h0623/picsView/blob/master/resources/js/pages/PhotoList.vue#L95-L100
    - 参考記事
        - https://qiita.com/akifo/items/4a8b7270dffedb1bcf59

- router.pushの修正
    - 以下の書き方は間違っている
         - https://github.com/michi-h0623/picsView/blob/master/resources/js/pages/PhotoDetail.vue#L136
    - 正しくは、 `this.$router.push({ path: '/' })`
         - https://router.vuejs.org/ja/guide/essentials/navigation.html

**Comment by michi-h0623** [comment]
ありがとうございます！

https://github.com/michi-h0623/picsView/blob/master/resources/js/pages/PhotoDetail.vue#L131

の、

if (response !== OK) {

が原因で、

if (response.status !== OK) {

とすると通りました！
